version: '3'

services:
  db:
    image: postgres:12.10
    ports:
      - "5432:5432"
  web: 
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "app.py"]



